name: Publish Rust Crate

on:
  push:
    branches:
      - stable 
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Login into crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Build
        run: cargo build --verbose

      - name: Publish to crates.io
        run: cargo publish
